# Generated by Django 5.2.1 on 2026-06-18 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
