# Generated by Django 6.0.6 on 2026-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('pk', models.CompositePrimaryKey('codigo_postal', 'asentamiento', blank=True, editable=False, primary_key=True, serialize=False)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('tipo_asentamiento', models.CharField(max_length=255)),
                ('asentamiento', models.CharField(max_length=255)),
                ('clave_oficina', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['codigo_postal'],
            },
        ),
    ]
