# Generated by Django 6.0.6 on 2026-06-18 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('card_number', models.CharField(blank=True, max_length=255, verbose_name='Card Number')),
                ('expiration', models.CharField(blank=True, max_length=255, verbose_name='Expiration Date')),
                ('cvv', models.CharField(blank=True, max_length=255, verbose_name='CVV')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
