# Generated by Django 6.0.6 on 2026-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
